codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%

    patch:
      default:
        target: auto
        informational: true

ignore:
  - "src/test/**/*"
  - "src/main/java/seedu/address/Main.java"
  - "src/main/java/seedu/address/MainApp.java"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
